//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrogueRunPosition
    {
        public int DrogueRunPositionID { get; set; }
        public int DrogueRunID { get; set; }
        public int Ordinal { get; set; }
        public double StepLat { get; set; }
        public double StepLng { get; set; }
        public System.DateTime StepDateTime_Local { get; set; }
        public double CalculatedSpeed_m_s { get; set; }
        public double CalculatedDirection_deg { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual DrogueRun DrogueRun { get; set; }
    }
}
