//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDistributionList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailDistributionList()
        {
            this.EmailDistributionListContacts = new HashSet<EmailDistributionListContact>();
        }
    
        public int EmailDistributionListID { get; set; }
        public int CountryTVItemID { get; set; }
        public string RegionName { get; set; }
        public int Ordinal { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailDistributionListContact> EmailDistributionListContacts { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
