//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainExceedance
    {
        public int RainExceedanceID { get; set; }
        public int RainExceedanceTVItemID { get; set; }
        public int StartMonth { get; set; }
        public int StartDay { get; set; }
        public int EndMonth { get; set; }
        public int EndDay { get; set; }
        public double RainMaximum_mm { get; set; }
        public Nullable<int> StakeholdersEmailDistributionListID { get; set; }
        public Nullable<int> OnlyStaffEmailDistributionListID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual EmailDistributionList EmailDistributionList { get; set; }
        public virtual EmailDistributionList EmailDistributionList1 { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
