//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSectionLanguage
    {
        public int ReportSectionLanguageID { get; set; }
        public int ReportSectionID { get; set; }
        public int Language { get; set; }
        public string ReportSectionName { get; set; }
        public int TranslationStatusReportSectionName { get; set; }
        public string ReportSectionText { get; set; }
        public int TranslationStatusReportSectionText { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual ReportSection ReportSection { get; set; }
    }
}
