//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportSection()
        {
            this.ReportSectionLanguages = new HashSet<ReportSectionLanguage>();
            this.ReportSections1 = new HashSet<ReportSection>();
            this.ReportSections11 = new HashSet<ReportSection>();
        }
    
        public int ReportSectionID { get; set; }
        public int ReportTypeID { get; set; }
        public Nullable<int> TVItemID { get; set; }
        public int Ordinal { get; set; }
        public bool IsStatic { get; set; }
        public Nullable<int> ParentReportSectionID { get; set; }
        public Nullable<int> Year { get; set; }
        public bool Locked { get; set; }
        public Nullable<int> TemplateReportSectionID { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSectionLanguage> ReportSectionLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSection> ReportSections1 { get; set; }
        public virtual ReportSection ReportSection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSection> ReportSections11 { get; set; }
        public virtual ReportSection ReportSection2 { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
