//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPAmbient
    {
        public int VPAmbientID { get; set; }
        public int VPScenarioID { get; set; }
        public int Row { get; set; }
        public Nullable<double> MeasurementDepth_m { get; set; }
        public Nullable<double> CurrentSpeed_m_s { get; set; }
        public Nullable<double> CurrentDirection_deg { get; set; }
        public Nullable<double> AmbientSalinity_PSU { get; set; }
        public Nullable<double> AmbientTemperature_C { get; set; }
        public Nullable<int> BackgroundConcentration_MPN_100ml { get; set; }
        public Nullable<double> PollutantDecayRate_per_day { get; set; }
        public Nullable<double> FarFieldCurrentSpeed_m_s { get; set; }
        public Nullable<double> FarFieldCurrentDirection_deg { get; set; }
        public Nullable<double> FarFieldDiffusionCoefficient { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual VPScenario VPScenario { get; set; }
    }
}
