//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdaterRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updater.Resources.UpdaterRes", typeof(UpdaterRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE 21 and 3 Dongle not found on the server..
        /// </summary>
        internal static string Mike21_3DongleNotFound {
            get {
                return ResourceManager.GetString("Mike21_3DongleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE 21 et 3 Dongle n&apos;ont pas été trouvés sur le serveur.
        /// </summary>
        internal static string Mike21_3DongleNotFound_fr {
            get {
                return ResourceManager.GetString("Mike21_3DongleNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running ... {0:F0} % completed ....
        /// </summary>
        internal static string Running_Completed {
            get {
                return ResourceManager.GetString("Running_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En exécution ... {0:F0} % complété ….
        /// </summary>
        internal static string Running_Completed_fr {
            get {
                return ResourceManager.GetString("Running_Completed_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario completed {0}.
        /// </summary>
        internal static string Scenario_Completed {
            get {
                return ResourceManager.GetString("Scenario_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scénario complèter {0}.
        /// </summary>
        internal static string Scenario_Completed_fr {
            get {
                return ResourceManager.GetString("Scenario_Completed_fr", resourceCulture);
            }
        }
    }
}
